linters:
    flake8:
        ignore: 'W28'
        max-line-length: 120
        max-complexity: 20

files:
        ignore: ['tests/vtk/*', 'tests/*', 'Tests/*', 'Fonts/*', 'Share/*', 'docs/*', 'scripts/*']

